/* tinyquant.h — Phase 11 placeholder.
 * Generated by cbindgen in Phase 22.
 */
#ifndef TINYQUANT_H
#define TINYQUANT_H

#include <stdint.h>

uint32_t tinyquant_version(void);

#endif /* TINYQUANT_H */
