//! C ABI façade for `TinyQuant`.
//!
//! Exposes a stable `extern "C"` surface for non-Rust consumers. The
//! header `include/tinyquant.h` is regenerated by `build.rs` via
//! [`cbindgen`] on every `cargo build -p tinyquant-sys`; CI fails on any
//! non-empty diff (see the Phase 22 plan §cbindgen drift guard).
//!
//! # Design invariants
//!
//! 1. Every `extern "C" fn` wraps its body in
//!    `std::panic::catch_unwind(AssertUnwindSafe(|| { ... }))` and maps
//!    any panic payload to [`error::TinyQuantErrorKind::Panic`] with the
//!    captured payload message. No panic ever crosses the boundary.
//! 2. Handles are opaque zero-sized structs (`_private: [u8; 0]`) in the
//!    [`handle`] module; their Rust counterparts live in the narrow
//!    `allow(unsafe_code)` modules ([`codec_abi`] and [`corpus_abi`]).
//! 3. Errors are surfaced through a caller-owned `TinyQuantError*`
//!    out-pointer whose `message` field must be freed by the caller with
//!    [`error::tq_error_free`].
//! 4. No `Box::leak`: every handle pointer is minted via `Box::into_raw`
//!    and reclaimed via `Box::from_raw` in its `_free` entry point.
//! 5. The crate is `#![forbid(unsafe_code)]` at the root; the only
//!    modules that override this with a narrow `#[allow(unsafe_code)]`
//!    are [`codec_abi`], [`corpus_abi`], and [`error`] (the latter
//!    because of its `CString::from_raw` free functions). See
//!    `docs/design/rust/phase-14-implementation-notes.md` §L7 for the
//!    narrow-allow pattern.
//!
//! # Version guard
//!
//! `TINYQUANT_H_VERSION` in the generated header is emitted from
//! `cbindgen.toml` via the `@version@` substitution and compared to
//! `env!("CARGO_PKG_VERSION")` at build time through a `const` sanity
//! check below. A mismatch is a compile-time error.
#![no_std]
// Intentionally `deny` rather than `forbid`: `forbid` cannot be
// narrowed by inner `#[allow(unsafe_code)]` attributes. Every module
// inherits this `deny`, and only the narrow-allow modules
// (`codec_abi`, `corpus_abi`, `error`) lift it — each with an explicit
// file-level comment explaining the unsafe surface. See
// `docs/design/rust/phase-14-implementation-notes.md` §L7.
#![deny(unsafe_code)]
#![deny(
    warnings,
    missing_docs,
    unsafe_op_in_unsafe_fn,
    clippy::all,
    clippy::pedantic,
    clippy::nursery,
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::cognitive_complexity
)]
#![allow(
    clippy::module_name_repetitions,
    clippy::must_use_candidate,
    // `TinyQuant` appears in dozens of doc comments; spelling it with
    // backticks everywhere would hurt readability.
    clippy::doc_markdown,
    // Small match arms that mirror the user-facing enum variants are
    // clearer than wildcard folds; the ABI layer deliberately preserves
    // explicit 1:1 variant mapping.
    clippy::match_same_arms,
    // `redundant_pub_crate` fires on crate-internal items in private
    // modules. In this crate the narrow-allow pattern means those items
    // are only callable from the `abi` modules; `pub(crate)` is the
    // accurate visibility.
    clippy::redundant_pub_crate
)]

extern crate alloc;
extern crate std;

pub mod codec_abi;
pub mod corpus_abi;
pub mod error;
pub mod handle;
mod internal;

// Note: `extern "C" fn` items with `#[no_mangle]` are exported at the
// symbol level regardless of their Rust-visibility. We intentionally do
// NOT re-export them at the crate root — doing so would cause cbindgen
// to emit each declaration twice (once when parsing `lib.rs`, once when
// parsing the defining module). Downstream Rust consumers that want to
// call them from Rust can go through `tinyquant_sys::codec_abi::*` etc.
pub use corpus_abi::TinyQuantCompressionPolicy;
pub use error::{TinyQuantError, TinyQuantErrorKind};
pub use handle::{
    ByteBufferHandle, CodebookHandle, CodecConfigHandle, CompressedVectorHandle, CorpusHandle,
};
