//! C ABI façade for `TinyQuant`.
//!
//! Exposes a stable `extern "C"` surface for non-Rust consumers. The
//! header `include/tinyquant.h` is regenerated by `build.rs` via
//! [`cbindgen`] on every `cargo build -p tinyquant-sys`; CI fails on any
//! non-empty diff (see the Phase 22 plan §cbindgen drift guard).
//!
//! # Design invariants
//!
//! 1. Every `extern "C" fn` wraps its body in
//!    `std::panic::catch_unwind(AssertUnwindSafe(|| { ... }))` and maps
//!    any panic payload to [`error::TinyQuantErrorKind::Panic`] with the
//!    captured payload message. No panic ever crosses the boundary.
//! 2. Handles are opaque zero-sized structs (`_private: [u8; 0]`) in the
//!    [`handle`] module; their Rust counterparts live in the narrow
//!    `allow(unsafe_code)` modules ([`codec_abi`] and [`corpus_abi`]).
//! 3. Errors are surfaced through a caller-owned `TinyQuantError*`
//!    out-pointer whose `message` field must be freed by the caller with
//!    [`error::tq_error_free`].
//! 4. No `Box::leak`: every handle pointer is minted via `Box::into_raw`
//!    and reclaimed via `Box::from_raw` in its `_free` entry point.
//! 5. The crate is `#![forbid(unsafe_code)]` at the root; the only
//!    modules that override this with a narrow `#[allow(unsafe_code)]`
//!    are [`codec_abi`], [`corpus_abi`], and [`error`] (the latter
//!    because of its `CString::from_raw` free functions). See
//!    `docs/design/rust/phase-14-implementation-notes.md` §L7 for the
//!    narrow-allow pattern.
//!
//! # Version guard
//!
//! `TINYQUANT_H_VERSION` in the generated header is emitted from the
//! `header` block in `cbindgen.toml`. The raw `@version@` token in
//! that block is NOT substituted by cbindgen under `with_src` (see
//! [`build.rs`] for context); instead the build script post-
//! processes the emitted header and replaces it with
//! `CARGO_PKG_VERSION`. A `const _: ()` block below byte-compares
//! [`TINYQUANT_H_VERSION`] (the manually-kept-in-sync constant) with
//! `env!("CARGO_PKG_VERSION")`. Any drift is a compile-time error.
#![no_std]
// Intentionally `deny` rather than `forbid`: `forbid` cannot be
// narrowed by inner `#[allow(unsafe_code)]` attributes. Every module
// inherits this `deny`, and only the narrow-allow modules
// (`codec_abi`, `corpus_abi`, `error`) lift it — each with an explicit
// file-level comment explaining the unsafe surface. See
// `docs/design/rust/phase-14-implementation-notes.md` §L7.
#![deny(unsafe_code)]
#![deny(
    warnings,
    missing_docs,
    unsafe_op_in_unsafe_fn,
    clippy::all,
    clippy::pedantic,
    clippy::nursery,
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::cognitive_complexity
)]
#![allow(
    clippy::module_name_repetitions,
    clippy::must_use_candidate,
    // `TinyQuant` appears in dozens of doc comments; spelling it with
    // backticks everywhere would hurt readability.
    clippy::doc_markdown,
    // Small match arms that mirror the user-facing enum variants are
    // clearer than wildcard folds; the ABI layer deliberately preserves
    // explicit 1:1 variant mapping.
    clippy::match_same_arms,
    // `redundant_pub_crate` fires on crate-internal items in private
    // modules. In this crate the narrow-allow pattern means those items
    // are only callable from the `abi` modules; `pub(crate)` is the
    // accurate visibility.
    clippy::redundant_pub_crate
)]

extern crate alloc;
extern crate std;

pub mod codec_abi;
pub mod corpus_abi;
pub mod error;
pub mod handle;
mod internal;

// Note: `extern "C" fn` items with `#[no_mangle]` are exported at the
// symbol level regardless of their Rust-visibility. We intentionally do
// NOT re-export them at the crate root — doing so would cause cbindgen
// to emit each declaration twice (once when parsing `lib.rs`, once when
// parsing the defining module). Downstream Rust consumers that want to
// call them from Rust can go through `tinyquant_sys::codec_abi::*` etc.
pub use corpus_abi::TinyQuantCompressionPolicy;
pub use error::{TinyQuantError, TinyQuantErrorKind};
pub use handle::{
    ByteBufferHandle, CodebookHandle, CodecConfigHandle, CompressedVectorHandle, CorpusHandle,
};

// ── Header / crate version parity check ──────────────────────────────
//
// `build.rs` post-processes `include/tinyquant.h` to substitute the
// `@version@` token in `cbindgen.toml`'s `header` block with the
// build-time value of `CARGO_PKG_VERSION`. `TINYQUANT_H_VERSION` below
// mirrors that substituted literal so the two can be byte-compared at
// compile time. Any drift (forgotten bump of this constant after a
// crate version change, stale committed header) is a compile-time
// error.
//
// Kept manually in sync with the workspace `version` field — this
// file MUST be updated in the same commit that bumps `rust/Cargo.toml`'s
// `[workspace.package] version = "..."`. The build script is NOT a
// safe place to put this check because `build.rs` runs at build time
// and has no way to refuse compilation of the crate itself; the
// `const` block below does.
/// Version string baked into the generated C header `TINYQUANT_H_VERSION`
/// macro. Must equal `env!("CARGO_PKG_VERSION")`; see the `const` block
/// below for the compile-time assertion.
pub const TINYQUANT_H_VERSION: &str = "0.1.0";

#[allow(clippy::indexing_slicing)]
const _: () = {
    let h = TINYQUANT_H_VERSION.as_bytes();
    let c = env!("CARGO_PKG_VERSION").as_bytes();
    assert!(
        h.len() == c.len(),
        "TINYQUANT_H_VERSION length differs from CARGO_PKG_VERSION — \
         update src/lib.rs TINYQUANT_H_VERSION to match the new crate \
         version, regenerate the C header, and commit both.",
    );
    let mut i = 0;
    while i < h.len() {
        assert!(
            h[i] == c[i],
            "TINYQUANT_H_VERSION differs from CARGO_PKG_VERSION — \
             the committed C header is out of sync with the crate \
             version. Update src/lib.rs TINYQUANT_H_VERSION and \
             rebuild to regenerate include/tinyquant.h.",
        );
        i += 1;
    }
};
